name: lint
on: [push]
jobs:
  ecs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Easy Coding Standard
        uses: pietrzakadrian/easy-coding-standard-github-action@v2.0.5
        with:
          config: ecs.php #configuration file
          directories: src tests #list of directories to check (optional)
